use_frameworks!

target 'ZMJGanttChart_Example' do
  pod 'ZMJGanttChart', :path => '../'

  target 'ZMJGanttChart_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end

target 'ZMJClassData' do
    pod 'ZMJGanttChart', :path => '../'
end

target 'ZMJTimeable' do
    pod 'ZMJGanttChart', :path => '../'
end

target 'ZMJSchedule' do
    pod 'ZMJGanttChart', :path => '../'
end
